apiVersion: v1
kind: Secret
metadata:
  name: qrcode-secret
  namespace: qrcode
type: Opaque
stringData:
  DB_PASSWORD: "replace_me"
  ADMIN_INITIAL_PASSWORD: "replace_me"
  AUTH_TOKEN_SECRET: "replace_me_with_a_random_secret_at_least_32_chars"
  WECHAT_MP_SECRET: "replace_me"
